export const VENOK_WS_ADAPTER_GET_OR_CREATE_SERVER = Symbol("VENOK_WS_ADAPTER_GET_OR_CREATE_SERVER");
export const VENOK_WS_ADAPTER_BIND_CLIENT_CONNECT = Symbol("VENOK_WS_ADAPTER_BIND_CLIENT_CONNECT");
export const VENOK_WS_ADAPTER_BIND_CLIENT_DISCONNECT = Symbol("VENOK_WS_ADAPTER_BIND_CLIENT_DISCONNECT");
export const VENOK_WS_ADAPTER_BIND_MESSAGE_HANDLERS = Symbol("VENOK_WS_ADAPTER_BIND_MESSAGE_HANDLERS");
export const VENOK_WS_ADAPTER_CREATE = Symbol("VENOK_WS_ADAPTER_CREATE");
export const VENOK_WS_ADAPTER_LISTEN = Symbol("VENOK_WS_ADAPTER_LISTEN");