export const VENOK_ADAPTER_BUILD = Symbol("VENOK_ADAPTER_BUILD");
export const VENOK_ADAPTER_ADD_ROUTE = Symbol("VENOK_ADAPTER_ADD_ROUTE");
export const VENOK_ADAPTER_ADD_MIDDLEWARE = Symbol("VENOK_ADAPTER_ADD_MIDDLEWARE");
export const VENOK_ADAPTER_SET_EXCEPTION_FILTER = Symbol("VENOK_ADAPTER_SET_EXCEPTION_FILTER");
export const VENOK_APPLY_ROUTES_TO_INSTANCE = Symbol("VENOK_APPLY_ROUTES_TO_INSTANCE");
export const VENOK_ADAPTER_RESPONSE = Symbol("VENOK_ADAPTER_RESPONSE");
export const VENOK_ADAPTER_TRANSFORM_NATIVE_ARGS_TO_CONTEXT = Symbol("VENOK_ADAPTER_TRANSFORM_NATIVE_ARGS_TO_CONTEXT");